archive_base_controller:
    pattern: /archive
    defaults: { _controller: o0johntam0o.archive.controller:base }

archive_view_forum_controller:
    pattern: /archive/{f}-{page}
    defaults: { _controller: o0johntam0o.archive.controller:base, f:0, page:0 }
    requirements:
        f: \d+

archive_view_topic_controller:
    pattern: /archive/{f}/{t}-{page}
    defaults: { _controller: o0johntam0o.archive.controller:base, f:0, t:0, page:0 }
    requirements:
        f: \d+
        t: \d+
